### ISSUE TITLE
(Better) build instructions for local build / self-hosted Seatable?

### ISSUE THREAD

**Issue by agrimpelhuber** [seatable/seatable-plugin-map#53]
I've come here straight from the forum, where it was stated that you have to build the plugin yourself in order to use it on self-hosted installations. Challenge accepted.

However, I struggle to get it running. I figured out a few things already (having to add setting.js because it's missing here, replaced it with the one from the plugin template), but now is the time that I have spent so much time that I'd rather ask here than waste more.

First Question: After having built and uploaded the plugin, is there anything else I need to do on the server to enable it. Seatable still tells me "The map plugin is not properly configured. Contact the administrator.". It doesn't even make a call to the Google API, so I guess I'm missing a server config.

Thanks!

**Comment by dorbak** [comment]
Having just gone through this, you need to modify the dtable_web_settings.py file (/opt/seatable/seatable-data/seatable/conf) with the key: 

DTABLE_GOOGLE_MAP_KEY = '`apikey from google`'

Check the bottom of this page:  https://manual.seatable.io/config/templates_and_manual/

Now I'm trying to figure out how to use the map...🤔

**Comment by agrimpelhuber** [comment]
@dorbak , you are wonderful - that's it. I've been barking up the wrong tree all along, misled by the forum entry of somebody who claimed that you have to compile the map plugin for on-premise use, baking in the APi key.

With the key in the conf file, I was able to use the plugin from the market.

How to use it is quite simple:
- Define a column of the type "position" - you will be able to pick a position from the map, and the coordinates will be written into the field
- Then you can configure the plugin to place all the entries from a table which have a location in a map overview.
